import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/aziz.jpg';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBuld from '../../public/images/svgs/miscellaneous_icons_1.svg';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full h-min dark:bg-dark dark:text-light pt-0">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="  w-full flex items-center justify-center text-center flex-col">
            <div className="md:w-full flex justify-start  items-center rounded-full ">
              <Image
                src={profilePic}
                alt="Ahmed"
                className=" rounded-full  md:inline-block md:mb-8 md:w-full "
                priority
                // width={90}
                // height={90}
                // sizes="(max-width: 8px) 100vw,
                // (max-width: 600px) 20vw, 20vw"
              />
            </div>
            <div className=" w-full flex flex-col items-center justify-center text-center self-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Ahmed Aziz"
                className="!text-6xl xl:text-5xl !text-center md:text-5xl sm:!text-3xl"
              />
              <AnimatedText
                text="SEO Specialist - Content Creator "
                className="!text-5xl xl:text-5xl self-center !text-center md:text-5xl sm:!text-3xl"
              />
              <div className="w-full flex gap-8 justify-center ">
                <p className="w-[90%] text-xl font-medium text-left flex justify-start px-3 ">
                  As a Junior SEO specialist and content creator, I have
                  experience in driving organic traffic and improving search
                  engine rankings through the creation of high-quality, engaging
                  content. With a strong understanding of keyword research,
                  on-page optimization techniques, and content management
                  systems, I have successfully increased website visibility for
                  multiple clients. My skills in writing, graphic design, and
                  social media management allow me to produce content that
                  resonates with target audiences and drives engagement.
                  Proficient in tools such as Google Analytics and WordPress, I
                  am constantly seeking new ways to improve my skills and
                  deliver results for my clients.
                </p>
                <div className="w-20 h-20">
                  <Image
                    src={lightBuld}
                    alt=" Ahmed Khaled"
                    className="w-full h-auto"
                  />
                </div>
              </div>

              <div className="flex items-center mt-5 self-center lg:gap-6">
                <Link
                  className=" mt-2 bg-dark text-light px-4 py-3
                  rounded-lg text-lg font-semibold hover:bg-light
                  hover:text-dark border flex flex-row
                  border-solid border-transparent
                  hover:border-dark dark:border-light
                   dark:p-4
                   "
                  href="/Ahmed_Aziz_SEO_specislist.pdf"
                  target={'_blank'}
                  download={true}
                >
                  Resume
                  <LinkArrow className={'w-6 ml-1 '} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium
                   capitalize text-dark dark:text-light underline"
                  href="mailto: ahmed.aziz900066@gmail.com"
                >
                  contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
